# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsoofDO5x1YBN7-cBd0CB4zFXL3Cxbse
"""

1 # while loop
2
i = 1

while i == 1:
  print(i)

  i = i+1

1 # print all even numbers between 0 to 20
for i in range(0,21):
    if i % 2 == 1:
      print(i)

for i in range(0,21):
  if i % 2 ==0:
    print(i)

# string data type


str =['hello,world,python programming']

for i in str:
  print(i)

1 # what are the methods of string
name = 'India'

print(type(name))


'''
note:
when any function defined inside a class it is called
" method of respective class"

'''

print(name.capitalize())
print(name.casefold())
print(name.lower())
print(name.upper())

name = [1,2,5,8,9]
str = ['A','D','B']

name.reverse()
print(name)
name.sort()
print(name)
print(str.sort())

names = ['chandan','anjali','rohit','priya','sneha']

for index, name in enumerate(names):
  print(f"Index:{index}, name:{name}")